apiVersion: v1
kind: Service
metadata:
  name: operations
  namespace: app
  labels:
    app: operations
spec:
  type: ClusterIP
  selector:
    app: operations
  ports:
    - name: http
      port: 8011
      targetPort: 8011
      appProtocol: http
